version: 2

models:
  - name: mong_bq
    columns:
      - name: _id
      - name: name
      - name: globalCustomerId
      - name: firebaseTokens
      - name: phoneNumbers
      - name: kids
      - name: kids._id
      - name: kids.name
      - name: kids.gender
      - name: kids.birthDate
      - name: kids.avatarId
      - name: kids.createdAt
      - name: kids.updatedAt
      - name: kids.wishList
      - name: kids.wishList._id
      - name: kids.wishList.products
      - name: kids.wishList.products.sku
      - name: kids.wishList.products.sortOrder
      - name: kids.wishList.products.isPurchased
      - name: kids.wishList.products.addedAt
      - name: kids.wishList.categoryIds
      - name: kids.wishList.brandIds
      - name: kids.wishList.title
      - name: kids.wishList.createdAt
      - name: kids.wishList.updatedAt
    tests:
      - unique: ["_id"]
